const STRATEGIES = [
  {
    id: "cross-platform-arb",
    type: "core",
    name: "Cross-platform arbitrage",
    badge: "Low risk",
    badgeType: "badge-green",
    desc: "Buy YES on one platform, NO on another when combined cost < $1.00. One side always wins — you collect the difference as guaranteed profit.",
    capital: "$2K+",
    returns: "3–10% per trade",
    timeframe: "Days",
    steps: [
      { title: "Fund both platforms simultaneously", text: "Split your starting capital 50/50 between Polymarket and Kalshi. You need live capital on both to execute both legs at the exact same time. Never leave one side unfilled — that's a naked directional bet." },
      { title: "Scan for gaps on eventarb.com daily", text: "Open eventarb.com every morning. It shows live pricing across Polymarket, Kalshi, Robinhood, and Interactive Brokers side by side. Filter for markets resolving within 14 days for best capital efficiency." },
      { title: "Calculate net profit after fees", text: "Formula: ($1.00 − YES price − NO price) minus Kalshi fees (~1.2% of contract value). You need a minimum gross gap of ~2.5¢ to profit after fees. Anything under that is not worth entering — the math doesn't work." },
      { title: "Verify resolution criteria match exactly", text: "Read both platforms' resolution rules word for word. The 2024 US government shutdown wiped out traders because Polymarket required 'OPM issues closure notice' while Kalshi required 'actual shutdown exceeding 24 hours'. They diverged — both sides lost." },
      { title: "Execute the illiquid side first", text: "Always execute the less liquid platform first (usually Kalshi), then immediately fill the Polymarket side. This minimises the risk of one leg filling while the other misses, leaving you with unhedged directional exposure." },
    ],
    tip: "Best markets: Fed rate decisions, sports results, and near-term crypto price windows. These have unambiguous resolution criteria and short timelines — the two things that make arb work cleanly.",
    warn: "Capital lockup is the hidden cost. A 7% return over 90 days is only 28% annualised. Rotate into short-resolution opportunities (under 14 days) to compound faster.",
    tools: ["eventarb.com", "defirate.com calculator", "Kalshi", "Polymarket"]
  },
  {
    id: "bond-strategy",
    type: "core",
    name: "High-probability bond strategy",
    badge: "Lowest risk",
    badgeType: "badge-green",
    desc: "Buy near-certain outcomes priced at 90–98¢. Hold to resolution at $1.00. Collect the spread as yield. No prediction required — just patience.",
    capital: "$1K+",
    returns: "2–11% per trade",
    timeframe: "2–14 days",
    steps: [
      { title: "Filter Polymarket by 'Ending Soon'", text: "Sort markets by closest resolution date. You want events resolving within 7 days. Then scan for YES prices sitting above 90¢. These are your candidates." },
      { title: "Check order book depth before entering", text: "Click into the market and check what's actually available at the top price. If you want $2,000 worth but only $500 is at 95¢ and the rest fills at 90¢, your effective yield drops sharply. Only enter if you can fill your target size within 2–3¢ of the advertised price." },
      { title: "Read the resolution criteria every single time", text: "A 97¢ market can still go to zero if the resolution standard is ambiguous. Never assume. Read the exact rules in every market before entering. Five minutes of reading can save you an entire position." },
      { title: "Place limit orders, never market orders", text: "A limit order 1–2¢ below the ask protects your yield. You may not fill instantly but you will not overpay. For very short resolution windows (under 48 hours), you can be more aggressive on price." },
      { title: "Stack 5–10 concurrent positions and recycle capital", text: "The real power of this strategy is compounding velocity. With 8 concurrent positions each returning 3–5% and resolving every 4–7 days, you are recycling capital faster than almost any other strategy on the platform." },
    ],
    tip: "Best bond trades: Fed holds rates (priced at 96¢ two days before the meeting), elections where results are already confirmed but markets haven't resolved, major sports results in the final hours before official settlement.",
    warn: "Never put more than 8% of total bankroll into a single bond trade no matter how certain it looks. A 96¢ market still has a 4% chance of going to zero — that is not zero.",
    tools: ["Polymarket 'Ending Soon' filter", "Dune Analytics", "Manual order book review"]
  },
  {
    id: "market-making",
    type: "core",
    name: "Market making / liquidity provision",
    badge: "Medium risk",
    badgeType: "badge-amber",
    desc: "Post both buy and sell orders simultaneously. Earn the spread on every round trip plus daily USDC rewards from Polymarket's LP program.",
    capital: "$5K+",
    returns: "0.2% of volume/month + rewards",
    timeframe: "Ongoing",
    steps: [
      { title: "Choose 2–3 high-volume markets you understand", text: "Start with political markets during active periods, major crypto price predictions, or upcoming macro events. High volume means more trades hitting your orders. Never market make on obscure thin markets — you'll get filled on one side with no offsetting flow." },
      { title: "Post two-sided limit orders around the midpoint", text: "If YES trades at 50¢, post a bid at 48¢ and ask at 52¢ — a 4¢ spread. As you gain experience, tighten to 2–3¢. Tighter spread earns a higher daily rewards score from Polymarket's LP program." },
      { title: "Monitor inventory imbalance daily", text: "If everyone buys YES from you all day and no one sells it back, you accumulate an unintended YES position. Log your net exposure every morning. If one side exceeds 30% of your MM capital, trim it by trading out the excess." },
      { title: "Pull ALL orders before known catalysts", text: "Before any scheduled news event — Fed announcements, election results, sports finishes — cancel every open limit order at least 30–60 minutes ahead. A 50/50 market can move to 90/10 in seconds. If your ask at 52¢ fills when the market should be at 90¢, you just lost 38¢ per share." },
      { title: "Collect rewards daily and reinvest", text: "Polymarket pays daily USDC rewards to qualifying LPs. Check your rewards dashboard every morning and reinvest into larger position sizes. At $100K working capital, rewards alone generate meaningful passive income before counting spread income." },
    ],
    tip: "New markets in their first 48 hours often have wide spreads (8–15¢) with no competition. Get in early before bots and other MMs arrive. The largest per-trade profits are made in the first day of a new market.",
    warn: "Adverse selection is the killer risk. One news event while your orders are live can wipe out weeks of spread income in minutes. Never leave orders open through known catalysts.",
    tools: ["Polymarket Rewards dashboard", "Polymarket order book UI", "Dune Analytics"]
  },
  {
    id: "whale-copying",
    type: "core",
    name: "Whale copying",
    badge: "Medium risk",
    badgeType: "badge-amber",
    desc: "Polymarket is fully transparent on-chain. Track consistently profitable large wallets, identify their high-conviction positions, and follow them with your own capital.",
    capital: "$500+",
    returns: "Variable, high ceiling",
    timeframe: "Per trade",
    steps: [
      { title: "Find real whales via Arkham + PolyTrack", text: "Go to intel.arkm.com, search the Polymarket contract (0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E), filter by value. Copy wallet addresses. Cross-reference on polymarketanalytics.com to get handles. On PolyTrack, filter for: 100+ trades, $50K+ net profit, active in the last 3 months." },
      { title: "Qualify before you follow", text: "Check their specialty — which market categories did they profit in? A political whale has no proven edge in sports markets. Check win rate on settled trades only (many wallets inflate win rates by never closing losers). Check if they hedge YES+NO on the same market — that is not a directional signal you can copy." },
      { title: "Wait for convergence across 2–3 wallets", text: "One whale could simply be wrong. When 2–3 of your tracked whales take the same position within a short window, that convergence is a significantly stronger signal than any single wallet move. Set up Telegram alerts via PolyMonit for your watchlist." },
      { title: "Check price slippage before entering", text: "After spotting a whale trade, compare the current price to their entry price. If the market has already moved more than 10% since they entered, the edge has likely been priced in — skip it. Only enter within 5–8% of their entry using a limit order." },
      { title: "Set your own exit rules before you enter", text: "Decide before entering: independent exits work best for most copy traders. Example rule: exit at 2× return OR if the market moves 20% against you, whichever comes first. Never change your exit plan mid-trade based on emotion or what the whale is doing." },
    ],
    tip: "Insider detection: look for NEW wallets (created under 30 days) with very few total trades but one massive position on an unusual or niche market. New wallet + large size + obscure market = potential insider. These are the highest-value signals on the platform.",
    warn: "Never copy a 'quant hedge' wallet blindly. They often hold both YES and NO across related markets as part of a delta-neutral strategy. Copying one leg gives you directional exposure they do not actually have.",
    tools: ["PolyMonit", "PolyTrack", "Arkham (intel.arkm.com)", "Ratio Discord bot", "polymarketanalytics.com"]
  },
  {
    id: "logical-arb",
    type: "rare",
    name: "Logical (combinatorial) arbitrage",
    badge: "Uncommon",
    badgeType: "badge-rare",
    desc: "Exploit mathematically impossible pricing between logically related markets on the same platform. No second platform needed. Pure logic-based guaranteed profit.",
    capital: "$1K+",
    returns: "3–8% per trade",
    timeframe: "Days to weeks",
    steps: [
      { title: "Learn the three types of logical violations", text: "Type 1 — Subset: 'Chiefs win Super Bowl' (28%) vs 'AFC team wins Super Bowl' (24%). AFC includes the Chiefs. AFC price CANNOT be lower — buy it. Type 2 — Bundle: In a multi-outcome winner-takes-all market, if all outcome prices sum to less than $1.00, buy them all. Type 3 — Overpriced bundle: If five candidate YES prices sum to $1.15, the market is overpriced — sell the overpriced outcomes." },
      { title: "Scan for violations systematically", text: "Manually search Polymarket for the same event across different market framings (e.g. search 'Super Bowl AFC' and compare with team-specific markets). Semi-automated: use Polymarket's Gamma API to pull all active markets, group by topic keyword, and compare implied probabilities in a spreadsheet." },
      { title: "Verify the logical relationship precisely", text: "Before entering, confirm that the two markets share an exact logical relationship — not just a thematic one. 'Chiefs win Super Bowl' IS a subset of 'AFC team wins Super Bowl' by definition. 'Trump wins' IS a subset of 'Republican wins' by definition. Confirm this before trading it." },
      { title: "Buy the underpriced side only", text: "Always buy the mathematically underpriced side. In the AFC example, buy 'AFC wins' at 24¢. You do not need to hedge the other side — you profit if any AFC team wins, which is more likely than just the Chiefs winning alone. Logic guarantees your profit, not prediction." },
      { title: "Exit on convergence or hold to resolution", text: "Either the mispricing corrects as other traders notice (sell into the correction for a faster return), or you hold to resolution and collect $1.00. Average observed hold for these trades is 2–3 days. Monitor daily." },
    ],
    tip: "Sports markets are the goldmine here. The fragmented structure — team markets, division markets, conference markets, champion markets — creates logical violations constantly. Especially productive during playoff seasons across NFL, NBA, and Champions League.",
    warn: "Confirming the logical relationship incorrectly is the primary risk. Always verify the exact resolution criteria before assuming two markets are logically linked. A team 'advancing to the final' does not automatically mean they 'won their conference' — check the exact wording.",
    tools: ["Polymarket Gamma API", "eventarb.com", "Custom Python/Excel scanner", "Keyword search on Polymarket"]
  },
  {
    id: "resolution-edge",
    type: "rare",
    name: "Resolution edge trading",
    badge: "Uncommon",
    badgeType: "badge-rare",
    desc: "Trade the gap between a confirmed real-world outcome and official market settlement. Buy confirmed winners still trading at 97–99¢ while waiting for the oracle to process.",
    capital: "$500+",
    returns: "1–6% in hours",
    timeframe: "Hours to 2 days",
    steps: [
      { title: "Understand the resolution lag", text: "When a real-world event concludes, Polymarket's UMA Optimistic Oracle takes 2 hours minimum — sometimes up to 48 hours — to process the official resolution. During this window, a fully settled market can still trade at 94–99¢ instead of $1.00. That's free money for patient capital." },
      { title: "Monitor official resolution sources in real time", text: "Every Polymarket market lists its official resolution source in the rules. Follow those exact sources — OPM.gov for government shutdowns, AP/Reuters for elections, official sports APIs for game results. When you see the official confirmation, immediately check if the corresponding Polymarket price has updated." },
      { title: "Buy the confirmed winner immediately", text: "Enter a limit order at 95–97¢ on the confirmed outcome. You are collecting the final 3–5¢ left by traders who couldn't wait 24–48 hours for official resolution. The outcome is already decided — you are just getting paid for patience." },
      { title: "Watch for retail impatience selling", text: "Many retail traders sell winning positions at 97–99¢ to redeploy capital to the next market. This creates a constant supply of near-settled YES shares at a discount. You become their exit liquidity — earning 1–3¢ per share for simply waiting." },
      { title: "Monitor the UMA challenge window", text: "After resolution is proposed, there is a 2-hour window where anyone can challenge the result. Only enter this strategy on completely unambiguous outcomes (game scores, Fed decisions, clear election calls). If challenged, your 'settled' position suddenly has outcome uncertainty again." },
    ],
    tip: "Best for: sports results (game ends, market still at 96¢), Fed rate decisions (announced, market still at 94¢), and economic data releases (CPI prints, market hasn't updated). These are clean, unambiguous, and almost never challenged.",
    warn: "Never use this on politically contested outcomes, ambiguous legal rulings, or any market where the resolution criteria could be disputed. Challenge risk is real on these — and a successful challenge can reset a 97¢ market back to 50¢.",
    tools: ["Polymarket resolution rules (read each market)", "UMA Oracle tracker", "OPM.gov, AP, Reuters, official sports APIs"]
  },
  {
    id: "quant-backtesting",
    type: "rare",
    name: "Quantitative backtesting signals",
    badge: "Uncommon",
    badgeType: "badge-rare",
    desc: "Use historical market data to find statistically exploitable pricing biases in recurring market types. Build repeatable systems, not one-off bets.",
    capital: "$2K+",
    returns: "High EV, variable",
    timeframe: "Recurring",
    steps: [
      { title: "Identify recurring market templates", text: "Polymarket has hundreds of recurring templates: 'Will BTC close above X this week?', 'Will Elon Musk post more than N tweets today?', 'Will the Fed raise/hold/cut?'. These repeat with consistent structure and are backtest-friendly. Pick one category with 50+ historical instances to start." },
      { title: "Pull historical data via Polymarket Gamma API", text: "Use gamma-api.polymarket.com to pull all historical markets matching your template. Export: opening price, closing price, volume, resolution outcome, days to resolution. Build a dataset of 50–100 instances minimum. Anything under 30 is noise, not signal." },
      { title: "Find systematic pricing biases", text: "Common patterns: Polymarket consistently overprices short-window crypto price movements due to retail excitement bias. Political markets tend to overprice incumbents in off-peak periods. Recurring data markets (CPI, NFP) often show directional bias in initial pricing vs actual outcomes. Your job is to quantify the bias." },
      { title: "Calculate Expected Value across all historical instances", text: "EV = (win probability × profit per win) − (loss probability × loss per loss). If the market historically prices YES at 55¢ but YES actually wins only 42% of the time, buying NO at 45¢ has strong positive EV. Run this over your full dataset — never cherry-pick." },
      { title: "Execute with Kelly sizing and track every trade", text: "Use Kelly criterion (bet size = edge / odds) but cap at half-Kelly for variance management. For a 10% edge with 1:1 odds, half-Kelly says bet 5% of bankroll. Log every trade with your pre-trade EV estimate. If actual results diverge from expected EV over 20+ trades, the signal may be decaying." },
    ],
    tip: "The Elon tweet count market is the famous example: a trader identified deterministic patterns in his historical post data and systematically exploited the crowd's mispricing for months. This approach works on any high-frequency recurring market where you can build a better model than the crowd.",
    warn: "Signals decay fast once they become known. Never discuss your working signals publicly. A profitable edge is destroyed the moment it's priced in by other traders. Treat your best patterns as trade secrets.",
    tools: ["Polymarket Gamma API", "Python (pandas, numpy)", "Excel for basic backtesting", "Dune Analytics SQL"]
  },
  {
    id: "news-momentum",
    type: "rare",
    name: "News momentum scalping",
    badge: "High risk",
    badgeType: "badge-red",
    desc: "Buy the first move on breaking news. Sell into the follow-through repricing as the crowd catches up. Requires speed, domain knowledge, and pre-built probability models.",
    capital: "$1K+",
    returns: "2–5% per trade, high frequency",
    timeframe: "Minutes to hours",
    steps: [
      { title: "Build a domain-specific news monitoring stack", text: "Pick ONE topic you understand deeply — crypto, Nigerian/African politics, specific sports leagues. Set up: X/Twitter keyword alerts, Google News alerts, Telegram channels for your domain. Speed is the entire edge here. You need to know about the news in the same second it breaks, not 30 seconds later." },
      { title: "Pre-build your probability models before news hits", text: "For every market you monitor, have a pre-built mental model of fair price under different news scenarios. Example: 'If Fed signals hawkish at today's press conference, this rate cut market should move from 55¢ to 30¢.' Pre-thinking is what lets you act in 5 seconds instead of 5 minutes." },
      { title: "Enter on the first price movement, not the headline", text: "When news breaks that matches your model, open Polymarket (have it pre-loaded on your phone or desktop) and buy the direction of the news before the market fully reprices. The window is 30 seconds to 3 minutes on major markets, 5–10 minutes on niche markets." },
      { title: "Sell into the follow-through, not at the peak", text: "Momentum trading is about selling as the crowd rushes to buy — not holding for maximum price. If you buy YES at 35¢ and it moves to 55¢ in 2 minutes, sell at 50–52¢. Do not wait for 65¢. Markets typically retrace 30–40% after the initial momentum burst." },
      { title: "Use volume spikes as your exit signal", text: "When trading volume on a market spikes 3–5× the average (visible in the trade history tab), that is the momentum peak. Other traders are piling in. That is your exit window — sell into their buying, not alongside it." },
    ],
    tip: "Your biggest personal edge: African political events, Nigerian CBN/SEC regulatory announcements, African football results. These are markets where you know the news before most Polymarket traders. Local information advantage is a real and exploitable edge on a global platform.",
    warn: "This is the highest-risk strategy in the playbook. A misread, a news retraction, or a market that already priced the news in means entering at the top and taking the full loss. Never size news momentum trades above 3% of bankroll per event.",
    tools: ["X/Twitter keyword alerts", "Telegram news channels", "Polymarket mobile (pre-loaded)", "Polymarket trade history volume tab"]
  }
];

const TOOLS = [
  { name: "eventarb.com", desc: "Real-time arb opportunities across Polymarket, Kalshi, Robinhood, and Interactive Brokers.", icon: "⚡", color: "#d4f53c", strategies: ["Cross-platform arb", "Logical arb"] },
  { name: "PolyMonit", desc: "Real-time whale wallet tracking with Telegram alerts by wallet address and trade size.", icon: "🔭", color: "#5c9eff", strategies: ["Whale copying", "Insider detection"] },
  { name: "PolyTrack", desc: "Filter top wallets by ROI, win rate, and volume. View trade history and open positions.", icon: "📊", color: "#4cde80", strategies: ["Whale copying"] },
  { name: "Arkham Intel", desc: "On-chain wallet intelligence. Search Polymarket contract to find largest positions.", icon: "🔍", color: "#a855f7", strategies: ["Whale copying", "Insider detection"] },
  { name: "Polymarket Gamma API", desc: "Pull historical market data for backtesting signals and building quantitative models.", icon: "🤖", color: "#f5a623", strategies: ["Backtesting", "Logical arb scanner"] },
  { name: "Dune Analytics", desc: "Custom SQL queries on Polymarket on-chain data. Volume tracking, wallet analysis.", icon: "🗃️", color: "#e879f9", strategies: ["Market making", "Bond strategy"] },
  { name: "Kalshi", desc: "Primary second platform for cross-platform arbitrage. US-regulated prediction market.", icon: "🏦", color: "#5c9eff", strategies: ["Cross-platform arb"] },
  { name: "Ratio Discord bot", desc: "Real-time whale watch feeds categorised by trade size. Cross-wallet correlation detection.", icon: "💬", color: "#5865f2", strategies: ["Whale copying"] },
];

const ALLOCATIONS = [
  { name: "Bond strategy", pct: 25, color: "#4cde80", reason: "Stable baseline yield. Low risk, short cycles, high capital velocity. Your income floor." },
  { name: "Market making", pct: 25, color: "#5c9eff", reason: "Passive spread income + daily USDC rewards. Earns while your other strategies are idle." },
  { name: "Logical arbitrage", pct: 15, color: "#d4f53c", reason: "Guaranteed profit on logic violations. Higher return than bonds, similar risk profile." },
  { name: "Whale copying", pct: 15, color: "#a855f7", reason: "Leverages smart-money research. Variable but high ceiling when signals converge." },
  { name: "Cross-platform arb", pct: 10, color: "#f5a623", reason: "When opportunities exist, act on them. Keep 10% allocated and ready to deploy fast." },
  { name: "Experimental / rare strategies", pct: 10, color: "#ff5c5c", reason: "Backtesting signals, resolution edge, news momentum. Higher variance, highest upside." },
];

const RULES = [
  { icon: "📐", name: "Kelly criterion sizing", text: "Never risk more than 5% of bankroll on a single trade. Use half-Kelly: for a 10% edge, bet 5% of capital, not 10%." },
  { icon: "⏱️", name: "Avoid capital lockup", text: "Long-duration markets tie up capital for months. Prioritise events resolving within 14 days. Velocity = compounding." },
  { icon: "🔄", name: "Diversify across markets", text: "Never concentrate in one category. Run 8–12 concurrent positions across different topics to smooth variance." },
  { icon: "📰", name: "Pull orders before catalysts", text: "Cancel all MM limit orders 30–60 minutes before any scheduled major event. Adverse selection kills weeks of profit in minutes." },
  { icon: "🧪", name: "Track every trade", text: "Log entry price, exit price, strategy used, and pre-trade thesis. Without data, you cannot know if an edge is decaying." },
  { icon: "🔐", name: "Guard your USDC", text: "Polymarket settles in USDC on Polygon. Keep only active working capital on-platform. Withdrawal is on-chain and fast." },
];
